apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
      app: demoapp
      role: backend
  name: demoapp 
  namespace: apowine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demoapp 
  template:
    metadata:
      labels:
          app: demoapp 
          role: backend
    spec:
      containers:
        - image: dimitrihub/demoapp 
          imagePullPolicy: Always
          name: demoapp 
---
kind: Service
apiVersion: v1
metadata:
  name: demo 
  namespace: apowine
spec:
  selector:
      app: demoapp 
      role: backend
  ports:
    - port: 80
      name: http 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  namespace: apowine 
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /public
        backend:
          serviceName: demo 
          servicePort: 80
      - path: /internal 
        backend:
          serviceName: demo 
          servicePort: 80
      - path: /admin 
        backend:
          serviceName: demo 
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: internal-client 
  namespace: apowine
  labels:
    role: client
    app: internal-client
    type: cli
spec:
  replicas: 3
  selector:
    matchLabels:
      app: internal-client
  template:
    metadata:
      name: apowine-internal-client
      labels:
        role: client
        app: internal-client
        type: cli
    spec:
      containers:
          - name: internal-client
            image: aporeto/apowine-clientcurl:latest
            env:
            - name: URI
              value: "demo.apowine.svc.cluster.local/internal"
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: admin-client 
  namespace: apowine
  labels:
    role: client
    app: admin-client
    type: cli
spec:
  replicas: 3
  selector:
    matchLabels:
      app: admin-client
  template:
    metadata:
      name: apowine-admin-client
      labels:
        role: client
        app: admin-client
        type: cli
    spec:
      containers:
          - name: admin-client
            image: aporeto/apowine-clientcurl:latest
            env:
            - name: URI
              value: "demo.apowine.svc.cluster.local/admin"
