kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: aporetos.config.istio.io
  labels:
    package: aporeto
    istio: mixer-adapter
spec:
  group: config.istio.io
  names:
    kind: aporeto
    plural: aporetos
    singular: aporeto
  scope: Namespaced
  version: v1alpha2
---