apiVersion: "config.istio.io/v1alpha2"
kind: authorization
metadata:
  name: requestcontext
  namespace: istio-system
spec:
  subject:
    user: source.user | ""
    groups: 
    properties:
      labels: source.labels 
      k8s:namespace: source.namespace | ""
      k8s:service: source.service 
      k8s:serviceAccount: source.serviceAccount | ""
      k8s:source : source.uid | ""
  action:
    namespace: destination.namespace | ""
    service: destination.service | ""
    method: request.method | ""
    path: request.path | ""
    properties:
      app: destination.labels["app"] | ""
      version: destination.labels["version"] | ""
      k8s:destination: destination.uid | ""
---
apiVersion: "config.istio.io/v1alpha2"
kind: aporeto
metadata:
  name: handler
  namespace: istio-system
spec:
  namespace: "/flash/istio/apowine"
  uri: "https://api.preprod.aporeto.us"
  certificate: |
    -----END CERTIFICATE-----
  key: | 
    -----END EC PRIVATE KEY-----
  ca: | 
    -----END CERTIFICATE-----
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: rbaccheck
  namespace: istio-system
spec:
  match: "true"
  actions:
  - handler: handler.aporeto
    instances:
    - requestcontext.authorization
