apiVersion: "config.istio.io/v1alpha2"
kind: authorization
metadata:
  name: requestcontext
  namespace: istio-system
spec:
  subject:
    user: source.user | ""
    groups: 
    properties:
      labels: source.labels 
      k8s:namespace: source.namespace | ""
      k8s:service: source.service 
      k8s:serviceAccount: source.serviceAccount | ""
      k8s:source : source.uid | ""
  action:
    namespace: destination.namespace | ""
    service: destination.service | ""
    method: request.method | ""
    path: request.path | ""
    properties:
      app: destination.labels["app"] | ""
      version: destination.labels["version"] | ""
      k8s:destination: destination.uid | ""
---
apiVersion: "config.istio.io/v1alpha2"
kind: aporeto
metadata:
  name: handler
  namespace: istio-system
spec:
  namespace: "/flash/istio/apowine"
  uri: "https://api.preprod.aporeto.us"
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIBkTCCATagAwIBAgIRAMXBlp0m6h/rq64E1LAejswwCgYIKoZIzj0EAwIwJDEi
    MCAGA1UEAxMZcHJlcHJvZCBQdWJsaWMgU2lnbmluZyBDQTAeFw0xODA1MjMxODE5
    MTFaFw0xODEwMjAwNzAwMDBaMDgxDjAMBgNVBAoTBWZsYXNoMRAwDgYDVQQLEwdh
    cG9yZXRvMRQwEgYDVQQDEwtpc3Rpb2NsaWVudDBZMBMGByqGSM49AgEGCCqGSM49
    AwEHA0IABMbTxV4z8MvwKguLD6QpAxiwt8+FOa20gnaV7sWKHM0YI3H3vUM3TfY6
    W56JqLSrfp5rvVXpJajgorsXuODqnOyjNTAzMA4GA1UdDwEB/wQEAwIFoDATBgNV
    HSUEDDAKBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMAoGCCqGSM49BAMCA0kAMEYC
    IQCd4Iv5Dgw0EPBD4863G+8wVG7RPu416MD479L/xNBAjQIhAJAh3rYSqbMhiuU8
    ct/8aOO2xbzdYNuvkUSVhl3LXiGG
    -----END CERTIFICATE-----
  key: | 
    -----BEGIN EC PRIVATE KEY-----
    Proc-Type: 4,ENCRYPTED
    DEK-Info: AES-256-CBC,c66f370fef572e56b1d956ce1eb5ee7c

    jTLFcksftVRYW5qDzMXJDAzu6+Sr+ps/BHOTGkyH3Ei33gMRG5LKv7zhYI1rF9Ug
    wWPmZ3QgJTwOL6bqnNr6k5hB9DT34urPYvslzYlWCilLvwtjYsJl4XGa0p52A8VE
    fHddwz8bizl7TBfW9lo06fgrM5dJmI0rQ2HuQhAPDyo=
    -----END EC PRIVATE KEY-----
  ca: | 
    -----BEGIN CERTIFICATE-----
    MIIBaDCCAQ6gAwIBAgIRANh/GGzQjWONTyPrM8fm40swCgYIKoZIzj0EAwIwIjEg
    MB4GA1UEAxMXcHJlcHJvZCBJbnRlcm1lZGlhdGUgQ0EwHhcNMTcxMTAxMTY0OTUw
    WhcNMjcwOTEwMTY0OTUwWjAkMSIwIAYDVQQDExlwcmVwcm9kIFB1YmxpYyBTaWdu
    aW5nIENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEGjH6YnIO8SXfkCp8Q0xD
    3QDJJRYCQpFmBSx8IHXWIZzYyjgsirweNaRKq+iDb4ig9NX9SKEIWEqrfVwxN8ws
    9qMjMCEwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0E
    AwIDSAAwRQIhAOdtjtu4SKTUI1gUmTCy11ae8ZkCNLIkwnM5dXv1Wsa1AiBX6rqs
    6nr+ZGtdAR20qSV2G2Ql/spnqKjYlYvPuR3yxw==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIBXTCCAQOgAwIBAgIQN0RSrm5drxTZUpHCuKIVgzAKBggqhkjOPQQDAjAaMRgw
    FgYDVQQDEw9wcmVwcm9kIFJvb3QgQ0EwHhcNMTcxMTAxMTY0OTUwWhcNMjcwOTEw
    MTY0OTUwWjAiMSAwHgYDVQQDExdwcmVwcm9kIEludGVybWVkaWF0ZSBDQTBZMBMG
    ByqGSM49AgEGCCqGSM49AwEHA0IABCGmj9OLHDoeoEjGUkP0zqQDBtXVw/1n2lY5
    nELNHVpFi1Nzq/LzDixs0eitc4c1BMElQuLkGtFkd/qXQJ7FFiOjIzAhMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0gAMEUCIQDm
    +3nEYYXzEGwIJ2QFz3UzF3LbtQJo4i/jb66hGq8qDQIgOtsG6W4zDXuddi7SDOJZ
    f88ybkUznIJiTLW0oXXub8k=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIBVDCB+6ADAgECAhAmFIAo846DFsaQUUiEM9fIMAoGCCqGSM49BAMCMBoxGDAW
    BgNVBAMTD3ByZXByb2QgUm9vdCBDQTAeFw0xNzExMDExNjQ5NTBaFw0yNzA5MTAx
    NjQ5NTBaMBoxGDAWBgNVBAMTD3ByZXByb2QgUm9vdCBDQTBZMBMGByqGSM49AgEG
    CCqGSM49AwEHA0IABEQpKYlbCCXPg7CV6+Wla9rz77AwaRMXMGm61b+r+BbzV9E8
    xEvqn1sD7+gHZFlZJgvLy0O0n7pQK6w7PVVbfJWjIzAhMA4GA1UdDwEB/wQEAwIB
    BjAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0gAMEUCIQDNSSm5MgCVUV6r
    aqktgh2Lg1qnpX9hn5w96aGavJ+EZwIgT32RuDDdmTXyNgOkw5Qg7LMbdwsVI2MF
    7W6gbSeC8VE=
    -----END CERTIFICATE-----
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: rbaccheck
  namespace: istio-system
spec:
  match: "true"
  actions:
  - handler: handler.aporeto
    instances:
    - requestcontext.authorization
